project:
  type: website
  output-dir: docs

execute:
  freeze: auto  # Re-render only when source changes

#bibliography: files/bib/references.bib
csl: files/bib/apa.csl

website:
  title: "Guías de escritura"
  site-url: "https://econpucp.github.io/"
  page-navigation: true 
  favicon: "/files/img/pucp-favicon-512.png"

  navbar: 
    pinned: true
    background: primary
    foreground: light
    right:
      - text: "Estudio de caso"
        file: caso/intro-01.qmd
        icon: book-half
      - text: "Tesis modelo"
        href: modelo.qmd
        icon: binoculars
      - text: "Recursos"
        file: resource/index.qmd
        icon: bookshelf
      - text: "Reglamentos"
        file: reglamentos/index.qmd
        icon: file-earmark-pdf

  sidebar:
    - title: "Estudio de caso"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Apuntes preliminares"
          contents:
            - caso/intro-01.qmd
            - caso/intro-02.qmd
            - caso/intro-03.qmd
        - section: "Contenido"
          contents:
            - caso/01-caso.qmd
            - caso/02-caso.qmd
            - caso/03-caso.qmd
            - caso/04-caso.qmd              
            - caso/05-caso.qmd
            - caso/06-caso.qmd
        - section: "Contenido repetido"
          contents:        
            - text: "Capítulo 1: El estudio de caso en las Ciencias Sociales"
              file: caso/01-caso.qmd
            - text: "Capítulo 2. La rigurosidad en el estudio de caso"
              file: caso/02-caso.qmd
            - text: "3: Capítulo 3"
              file: caso/03-caso.qmd
            - text: "4: Capítulo 4"
              file: caso/04-caso.qmd              
            - text: "5: Capítulo 5"
              file: caso/05-caso.qmd
            - text: "6: Capítulo 6"
              file: caso/05-caso.qmd

    - title: "Tesis modelo"
      contents:
        - section: "Objetivo"
          contents:
            - example/index.qmd
        - section: "Ejemplos por especialidad"
          contents:
            - text: "Random numbers"
              file: example/random-numbers.qmd
            - text: "Synthetic data"
              file: example/synthetic-data.qmd
        - section: "Sección 3"
          contents:

  page-footer:
    left: |
      Content <i class="bi bi-cc-circle"></i> {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Proyecto elaborado para la [facultad de Ciencias Sociales de la PUCP](https://facultad.pucp.edu.pe/ciencias-sociales/)

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
  pdf:
    documentclass: scrreprt
