project:
  type: website
  output-dir: docs

execute:
  freeze: auto  # Re-render only when source changes

#bibliography: files/bib/references.bib
csl: files/bib/apa.csl

website:
  title: "Guías de escritura"
  site-url: "https://econpucp.github.io/"
  page-navigation: true 
  favicon: "/files/img/pucp-favicon-512.png"

  navbar: 
    pinned: true
    background: primary
    foreground: light
    right:
      - text: "Estudio de caso"
        file: caso/index.qmd
        icon: book-half
      - text: "Ejemplos"
        href: ej/tipo.qmd
        icon: binoculars
      - text: "Recursos"
        file: resource/index.qmd
        icon: bookshelf
      - text: "Reglamentos"
        file: reglamentos/index.qmd
        icon: file-earmark-pdf

  sidebar:
    - title: "Estudio de caso"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Prefacio"
          contents:
            - text: "Propuesta"
              file: caso/index.qmd
            - caso/intro-01.qmd
            - caso/intro-02.qmd
            - caso/intro-03.qmd
        - section: "Contenido"
          contents:
            - caso/01-caso.qmd
            - caso/02-caso.qmd
            - caso/03-caso.qmd
            - caso/04-caso.qmd              
            - caso/05-caso.qmd
            - caso/06-caso.qmd
            - caso/testing-code.qmd

        - section: "Ejemplos"
          contents:
            - ej/arrunategui2020.qmd
            - ej/otero2022.qmd
            
    - title: "Ejemplos"
      contents:
            - ej/tipo.qmd
            - ej/especialidad.qmd

    - title: "Recursos"
      contents:
            - resource/index.qmd
            - resource/rubrica.qmd
            - reglamentos/index.qmd

    - title: "Reglamentos"
      contents:
            - reglamentos/index.qmd

  page-footer:
    left: |
      Content <i class="bi bi-cc-circle"></i> {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Proyecto elaborado para la [facultad de Ciencias Sociales de la PUCP](https://facultad.pucp.edu.pe/ciencias-sociales/)

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
  pdf:
    documentclass: scrreprt
